export const SIGNUP_REQUESTING = 'SIGNUP_REQUESTING'

export const CLIENT_SET = 'CLIENT_SET'
export const CLIENT_UNSET = 'CLIENT_UNSET'
export const CLIENT_UNSET_SUCCESS = 'CLIENT_UNSET_SUCCESS'

export const LOGIN_REQUESTING = 'LOGIN_REQUESTING'

export const CREATE_CHAT_REQUESTING = 'CREATE_CHAT_REQUESTING'
export const CREATE_CHAT_SUCCESS = 'CREATE_CHAT_SUCCESS'
export const CREATE_CHAT_ERROR = 'CREATE_CHAT_ERROR'

export const GET_CHATS_REQUESTING = 'GET_CHATS_REQUESTING'
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS'
export const GET_CHATS_FAILURE = 'GET_CHATS_FAILURE'

export const GET_CHAT_REQUESTING = 'GET_CHAT_REQUESTING'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'
export const GET_CHAT_FAILURE = 'GET_CHAT_FAILURE'

export const JOIN_CHAT_REQUESTING = 'JOIN_CHAT_REQUESTING'
export const SEND_MESSAGE = 'SEND_MESSAGE'

export const DOWNLOAD_MESSAGES = 'DOWNLOAD_MESSAGES'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const CLEAR_OUT_CHAT = 'CLEAR_OUT_CHAT'

export const USER_CONNECTED = 'USER_CONNECTED'
export const USER_DISCONNECTED = 'USER_DISCONNECTED'
